### ISSUE TITLE
Bot crashes when playing age restricted video

### ISSUE THREAD

**Issue by Nick-NCSU** [Adamlip1334/dubnation-bot#14]

**Comment by Adamlip1334** [comment]
interesting, maybe you can try and a try catch and see if that works

**Comment by Nick-NCSU** [comment]
> interesting, maybe you can try and a try catch and see if that works

Issue occurred within a promise which needed to be handled asynchronously so .catch was used rather than a try catch block.

**Comment by Nick-NCSU** [comment]
Issue occurs with new ytdl
